import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Theme from "./components/ThemeToggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //  className={inter.className}>
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-[#e6e6e6] text-black dark:bg-[#122131] dark:text-[#e6e6e6]">
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
